### ISSUE TITLE
Can't import wheel.pep425tags

### ISSUE THREAD

**Issue by mengyaoxue** [samb8s/PsrPopPy#10]
When I try to install the latest version using `sudo python setup.py install`, I met an error of unable to `import wheel.pep425tags` in line 19 of SConstruct.
I take a look at my pip and wheel, and found that I'm using 'pip 21.0.1' and 'wheel 0.35.1', where they are using pep517.
I'm just wondering how can I do the installation?

**Comment by samb8s** [comment]
what python version are you using?

**Comment by mengyaoxue** [comment]
I have both Python 3.8.7 and Python 2.7.18 on my computer

**Comment by samb8s** [comment]
can you make sure you're using python2.7? 
I didn't write the setup.py so I can't help much on that. I've not heard of others having similar issues, though

**Comment by mengyaoxue** [comment]
Finally, instead of using the setup.py, I add the python code directory into the $PATH and $PYTHONPATH in my .bashrc manually. Thanks a lot anyway!
