### ISSUE TITLE
How to fix EnvironmentError: [Errno 2] No such file or directory: '/tmp/tmpFWwq5p/output.json'?

### ISSUE THREAD

**Issue by juejac** [samb8s/PsrPopPy#15]
I am trying to install the package on my ubuntu 22.04 system but have been running into this error:

> ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/tmpFWwq5p/output.json'

I installed the same package on a debian 10 system with no problems.

**Comment by samb8s** [comment]
OK, thanks - I suggest you try and debug the issue. I cannot reproduce it.
